.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH HOMEBANK 1 "Dec 22, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
homebank \- manage your personal accounts at home
.SH SYNOPSIS
.B homebank
[OPTION...] [FILE]
.SH DESCRIPTION
This manual page documents briefly the
.B homebank
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBhomebank\fP is a simple and easy to use program to manage your accounts.
It has a lot of features such as statistics with graphical charts, 
multi-accounts support, budget management, reminder, and even more!
.SH OPTIONS
.SS "Help Options:"
.TP
.BI \-?,\ \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.SS "Application Options:"
.TP
\fB\-\-version
Output version information and exit
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.TP
.SH SEE ALSO
\fIhttp://homebank.free.fr/\fR
.SH AUTHOR
\fBhomebank\fP was written by Maxime Doyen <homebank@free.fr>.
.PP
This manual page was written by Adrien Cunin <adri2000@ubuntu.com>
and by Francesco Namuri <francesco@namuri.it>,
for the Debian project (but may be used by others).
